Browser : Edge
ChromeDriverClassName : webdriver.chrome.driver
ChromeDriverClassPath : D:\\Prathamesh\\Selenium\\Supported_JarFiles\\chromedriver-win64\\chromedriver.exe

EdgeDriverClassName : webdriver.edge.driver
EdgeDriverClassPath : D:\\Prathamesh\\Selenium\\Supported_JarFiles\\msedgedriver.exe

Grid : NoGrid
GridURL : http://localhost:4444/wd/hub

AppURL : https://admin-demo.nopcommerce.com/login
UserName : admin@yourstore.com
Password : admin

DBurl : jdbc:mysql://localhost:3306/nopcommerce
DBUserName : root
DBPassword : root