DriverClassName : webdriver.chrome.driver
DriverClassPath : D:\\Prathamesh\\Selenium\\Supported_JarFiles\\Drivers\\chromedriver-win64\\chromedriver.exe

AppURL : https://admin-demo.nopcommerce.com/login
UserName : admin@yourstore.com
Password : admin

DBurl : jdbc:mysql://localhost:3306/nopcommerce
DBUserName : root
DBPassword : root